import * as React from 'react';
import { createRoot } from 'react-dom/client';
import { App } from './core'

// import layered css styles generated by panda
import './index.css';

// import i18n config
import './i18n';

createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
